out_dir_name = "<CONF_FILE_NAME>"
suffix = false
batch_size_eval = 256

[data]
path = "~/dataset/weather/weather.csv"
colname_timestamp = "date"
white_list = [
"p (mbar)",
"T (degC)",
# "Tpot (K)",
"Tdew (degC)",
"rh (%)",
# "VPmax (mbar)",
# "VPact (mbar)",
# "VPdef (mbar)",
# "sh (g/kg)",
# "H2OC (mmol/mol)",
# "rho (g/m**3)",
"wv (m/s)",
"max. wv (m/s)",
"wd (deg)",
"rain (mm)",
"raining (s)",
"SWDR (W/m^2)",
"PAR (umol/m^2/s)",
"max. PAR (umol/m^2/s)",
"Tlog (degC)",
# "OT",
]
seq_len = [6, 24, 4]
pred_len = [6, 24]

# -------------------- models --------------------

[[models]]
path = "shiroinu.models.simple_average.SimpleAverage"
[models.params]
seq_len = [6, 24, 4]
pred_len = [6, 24]
period_len = [6, 24]
[models.report]
name = "SA"

[[models]]
path = "shiroinu.models.simple_average.SimpleAverage"
[models.params]
seq_len = [6, 24, 4]
pred_len = [6, 24]
period_len = [6, 24]
decay_rate = 0.9
[models.report]
name = "SA09"

[[models]]
path = "shiroinu.models.simple_average.SimpleAverage"
[models.params]
seq_len = [6, 24, 4]
pred_len = [6, 24]
period_len = [6, 24]
decay_rate = 0.8
[models.report]
name = "SA08"

[[models]]
path = "shiroinu.models.simple_average.SimpleAverage"
[models.params]
seq_len = [6, 24, 4]
pred_len = [6, 24]
period_len = [6, 24]
decay_rate = 0.7
[models.report]
name = "SA07"

[[models]]
path = "shiroinu.models.simple_average.SimpleAverage"
[models.params]
seq_len = [6, 24, 4]
pred_len = [6, 24]
period_len = [6, 24]
decay_rate = 0.6
[models.report]
name = "SA06"

[[models]]
path = "shiroinu.models.simple_average.SimpleAverage"
[models.params]
seq_len = [6, 24, 4]
pred_len = [6, 24]
period_len = [6, 24]
decay_rate = 0.5
[models.report]
name = "SA05"

# -------------------- tasks --------------------

[[tasks]]
task_type = "eval"
valid_range = [0.8, 1.0]
models = [
{ id = 0, state_path = "" },
{ id = 1, state_path = "" },
{ id = 2, state_path = "" },
{ id = 3, state_path = "" },
{ id = 4, state_path = "" },
{ id = 5, state_path = "" },
]
percentile_points = [0.05, 0.25, 0.5, 0.75, 0.95]
[tasks.criterion_eval]
path = "shiroinu.criteria.MAELoss"
params = {}
